# Generated by Django 5.2.4 on 2025-08-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_project_projectselection"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="prj_number",
        ),
        migrations.RemoveField(
            model_name="project",
            name="prj_title",
        ),
        migrations.AddField(
            model_name="project",
            name="project_number",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="project_title",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.DeleteModel(
            name="ProjectSelection",
        ),
    ]
