# Generated by Django 5.2.4 on 2025-08-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_project_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprojectselection',
            name='choice_priority',
            field=models.IntegerField(choices=[(1, '1st Choice'), (2, '2nd Choice'), (3, '3rd Choice')], null=True),
        ),
    ]
