# Generated by Django 5.2.4 on 2025-08-31 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_userprojectselection_choice_priority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('OPEN', 'Open for Selection'), ('PROCESSING', 'Processing Assignments'), ('COMPLETED', 'Completed')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-round_number'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='assigned_student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprojectselection',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='userprojectselection',
            name='allocation_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.allocationround'),
        ),
        migrations.AlterUniqueTogether(
            name='userprojectselection',
            unique_together={('user', 'choice_priority', 'allocation_round')},
        ),
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('priority_level', models.IntegerField()),
                ('assigned_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.allocationround')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='base.project')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
